version: '3.7'
services:
  postgres:
    image: postgres:13-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    ports:
      - '5132:5432'

  adminer:
    image: adminer

    ports:
      - 8080:8080

volumes:
  pgdata:
