version: '3.7'
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    ports:
      - '5132:5432'

    restart: unless-stopped
